language: node_js
node_js:
  - "0.12"
  - "4"
sudo: false
services:
  - rabbitmq
  - mongodb
before_install:
  - npm install -g npm@latest
before_script:
  - ulimit -n 10240
script:
  - npm run lint
  - npm run unit
  - npm run functional

